services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        working_dir: /var/www
        restart:  unless-stopped
        volumes:
            - .:/var/www
        networks:
            - application

    db:
        image: mysql:5.7.22
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: help_desk
            MYSQL_ROOT_PASSWORD: root
        ports:
            - '3388:3306'
        volumes:
            - .db:/var/lib/postgresql/data
        networks:
            - application
    # db-test:
    #     image: postgres:16
    #     restart:  unless-stopped
    #     environment:
    #         - POSTGRES_PASSWORD=root
    #         - POSTGRES_DB=testing
    #         - POSTGRES_USER=root
    #     ports:
    #         - '9000:5432'
    #     volumes:
    #         - .docker/pgsql/db-test:/var/lib/postgresql/data
    #     networks:
    #         - application
    nginx:
        image: nginx:1.27
        restart: unless-stopped
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - application

networks:
    application:
        driver: bridge
